name:                tagnome
version:             0.1.0.0
github:              "ruly-rudel/tagnome"
license:             MIT
author:              "Ruly Rudel"
maintainer:          "ruly.rudel@gmail.com"
copyright:           "2021 Ruly Rudel"

extra-source-files:
- README.md
- CHARTER.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ruly-rudel/tagnome#readme>

dependencies:
- base >= 4.7 && < 5
- unliftio
- bytestring
- mmap
- string-conversions
- text
- unicode-show
- exceptions
- transformers
- mtl

library:
  source-dirs: src

executables:
  tagnome-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tagnome

tests:
  tagnome-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tagnome
    - HUnit
